import React from 'react';
import { SchoolConfig } from '../../../../types';
import ParentPayments from '../../../../apps/expo/app/parent/payments';
import TransportTracking from '../../../../apps/expo/app/parent/transport';
import { Gradebook } from '../academics/Gradebook'; // Using Gradebook as read-only view logic for MVP

interface Props {
  school: SchoolConfig;
  activeModule: string;
}

export const ParentDashboard: React.FC<Props> = ({ school, activeModule }) => {
  
  return (
    <div className="p-4 md:p-6 max-w-lg mx-auto md:max-w-4xl">
      {/* Parent Content is usually consumed on mobile, so we keep containers narrower */}
      
      {activeModule === 'FEES' && (
        <ParentPayments />
      )}

      {activeModule === 'TRACKING' && (
        <div className="space-y-4">
          <h2 className="text-xl font-bold text-gray-800">Live Bus Tracking</h2>
          <TransportTracking />
        </div>
      )}

      {activeModule === 'REPORT' && (
        <div className="space-y-4">
          <h2 className="text-xl font-bold text-gray-800">Student Report Card</h2>
          <div className="bg-white p-4 rounded-xl border border-gray-200 shadow-sm">
             <div className="flex items-center gap-4 mb-6 border-b pb-4">
                <div className="w-12 h-12 bg-gray-200 rounded-full flex items-center justify-center text-xl">🎓</div>
                <div>
                  <h3 className="font-bold text-lg">Aarav Kumar</h3>
                  <p className="text-xs text-gray-500">Class X-A • Roll No. 01</p>
                </div>
             </div>
             {/* Reusing Gradebook component - In a real app, this would be a ReadOnly prop */}
             <div className="pointer-events-none opacity-90">
                <Gradebook />
             </div>
             <p className="text-center text-xs text-gray-400 mt-4">
               Official Report Card generated by Sovereign ERP.
             </p>
          </div>
        </div>
      )}
    </div>
  );
};
