
import React from 'react';
import { SchoolConfig } from '../../../../types';
import ParentPayments from '../../../../apps/expo/app/parent/payments';
import TransportTracking from '../../../../apps/expo/app/parent/transport';
import { Gradebook } from '../academics/Gradebook'; // Read-only view
import { StatCard, PageHeader } from '../../components/SovereignComponents';
import { Wallet, Bus, FileText, CheckCircle } from 'lucide-react';

interface Props {
  school: SchoolConfig;
  activeModule: string;
}

export const ParentDashboard: React.FC<Props> = ({ school, activeModule }) => {
  return (
    <div className="p-4 md:p-8 max-w-4xl mx-auto">
      <PageHeader 
        title="Student Portal" 
        subtitle="Aarav Kumar • Class X-A" 
      />

      {/* KPI GRID */}
      <div className="grid grid-cols-2 md:grid-cols-4 gap-4 mb-8">
         <StatCard title="Fees Due" value="₹2,450" icon={<Wallet className="w-5 h-5" />} />
         <StatCard title="Attendance" value="92%" trend={{ value: 5, isPositive: true }} icon={<CheckCircle className="w-5 h-5" />} />
         <StatCard title="Bus Status" value="On Time" subtitle="Arriving 4:10 PM" icon={<Bus className="w-5 h-5" />} />
         <StatCard title="Report Card" value="A+" subtitle="Term 1 Result" icon={<FileText className="w-5 h-5" />} />
      </div>
      
      {activeModule === 'FEES' && <ParentPayments />}

      {activeModule === 'TRACKING' && (
        <div className="bg-white rounded-xl shadow-sm border border-gray-200 p-4">
          <h2 className="text-lg font-bold text-gray-800 mb-4">Live Bus Tracking</h2>
          <TransportTracking />
        </div>
      )}

      {activeModule === 'REPORT' && (
        <div className="bg-white p-6 rounded-xl border border-gray-200 shadow-sm">
             <h2 className="text-xl font-bold text-gray-800 mb-6">Academic Performance</h2>
             <div className="pointer-events-none opacity-90 scale-95 origin-top">
                <Gradebook />
             </div>
             <p className="text-center text-xs text-gray-400 mt-4">
               Official Report Card generated by Sovereign ERP.
             </p>
        </div>
      )}
    </div>
  );
};
